style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/bschaatsbergen/terraform-aws-alb-module
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject